### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by mrister** [jkernech/node-turl#1]
http**s**://tinyurl.com/api-create.php?url=${encodeURIComponent(url)}

**Comment by jkernech** [comment]
@mrister I just did a PR to support HTTPS since it's finally supported 🎉
Thank you!

**Comment by jkernech** [comment]
@mrister Thank you!

I just did a PR to support HTTPS since it's finally supported, unfortunately their API doesn't return HTTPS short links for now, I contacted them to know if they support the feature

**Comment by jkernech** [comment]
Response from TinyUrl support... 🤦‍♂️ 
> All TinyURLs can be accessed using either http or https. For the output of the API, you can add in the S in your app.
